name: Build and deploy ASP.Net Core app to Azure Web App - DeckDuelDemo API

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  test-secrets:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Echo secret
        run: echo "Secret present? ${{ secrets.AZURE_CLIENT_SECRET != '' }}"
